version: '3'

services:
    face_swap:
      build: .
      image: face_swap
      container_name: face_swap
      ports:
        - 8006:8006
      command: "uvicorn main:app --host 0.0.0.0 --port 8006 --reload --log-level debug"
      volumes:
        - ./:/server
      deploy:
        resources:
          reservations:
            devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

      restart: always


