version: '3'

services:
    face_swap:
      build: .
      image: face_swap
      container_name: face_swap
      ports:
        - 8006:8006
      command: "uvicorn main:app --host 0.0.0.0 --port 8006 --reload --log-level debug"


      restart: always


